pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/jenkins-jenkins-agent: true
spec:
  serviceAccountName: default
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.11.2-4
    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-volume
  - name: shell
    image: node:18
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-volume
  volumes:
  - name: workspace-volume
    emptyDir: {}
'''
            defaultContainer 'shell'
        }
    }
    
    environment {
        FIREBASE_TOKEN = credentials('firebase-token')
    }
    
    stages {
        stage('Setup') {
            steps {
                sh 'npm install -g firebase-tools'
                sh 'cd function-source_nodejs18 && npm install'
            }
        }
        
        stage('Build') {
            steps {
                sh 'cd function-source_nodejs18 && npm run build'
            }
        }
        
        stage('Test') {
            steps {
                sh 'cd function-source_nodejs18 && npm test'
            }
        }
        
        stage('Deploy') {
            steps {
                sh '''
                    cd function-source_nodejs18
                    firebase use ${FIREBASE_PROJECT} --token ${FIREBASE_TOKEN}
                    firebase deploy --only functions --token ${FIREBASE_TOKEN}
                '''
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
