---
apiVersion: v1
kind: Pod
metadata:
  name: "odyssey-server"
  labels:
    name: odyssey-server
    app: odyssey-server
    organizationId: "undefined"
    roomId: "undefined"
    firebaseProjectId: ""
    unrealProjectId: ""
    unrealProjectVersionId: ""
    buildPluginVersionId: ""
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - ORD1
  imagePullSecrets:
    - name: ngp-odyssey-gcr-read
  automountServiceAccountToken: false
  restartPolicy: Always
  containers:
    - name: unreal
      image: gcr.io/ngp-odyssey/odyssey-server:latest
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 1000m
          memory: 3Gi
        limits:
          cpu: 1000m
          memory: 3Gi
      command: ["/odyssey-server-entrypoint"]
      env:
        - name: FIREBASE_PROJECT_ID
          value: ""
        - name: FIREBASE_API_KEY
          value: ""
        - name: ORGANIZATION_ID
          value: ""
        - name: ROOM_ID
          value: ""
        - name: ENVIRONMENT_MAP
          value: ""
        - name: BASE_CLI_ARGS
          value: ""
        - name: OVERRIDE_CLI_ARGS
          value: ""
      ports:
        - containerPort: 7777
          hostPort: 7777
          protocol: UDP
      volumeMounts:
        - name: config-volume
          mountPath: /config-volume
        - name: config-volume
          mountPath: /odyssey-server-entrypoint
          subPath: odyssey-server-entrypoint
        - name: tmp
          mountPath: /tmp
    - name: firebase-bridge
      image: gcr.io/ngp-odyssey/firebase-bridge:latest
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 256m
          memory: 256Mi
        limits:
          cpu: 256m
          memory: 256Mi
      env:
        - name: ORGANIZATION_ID
          value: ""
        - name: ROOM_ID
          value: ""
        - name: SPACE_ID
          value: ""
      volumeMounts:
        - mountPath: /usr/src/app/logs
          subPath: logs/firebase-bridge
          name: logs
        - name: firebase-write-serviceaccount
          mountPath: /firebase-write-serviceaccount
    - name: fluentd
      image: gcr.io/ngp-odyssey/fluentd-bigquery:1
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
      env:
        - name: FIREBASE_PROJECT_ID
          value: ""
        - name: ORGANIZATION_ID
          value: ""
        - name: FIREBASE_EMULATOR
          value: ""
        - name: ROOM_ID
          value: ""
        - name: ENVIRONMENT_MAP
          value: ""
        - name: ODYSSEY_UE4_VERSION
          value: ""
        - name: UNREAL_PROJECT_ID
          value: ""
        - name: UNREAL_PROJECT_VERSION_ID
          value: ""
        - name: BUILD_PLUGIN_VERSION_ID
          value: ""
        - name: KUBERNETES_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: bigquery-writer-serviceaccount
          mountPath: /secret
        - name: logs
          mountPath: /logs/
          subPath: logs/
    - name: script-exporter
      image: ricoberger/script_exporter:v2.5.2
      args:
        - -config.file=/etc/script_exporter/config.yaml
      ports:
        - name: script-exporter
          containerPort: 9469
          protocol: TCP
      requests:
        cpu: 256m
        memory: 256Mi
      limits:
        cpu: 256m
        memory: 256Mi
      volumeMounts:
        - name: config-volume
          mountPath: /etc/script_exporter/odyssey-server.sh
          subPath: script_exporter-odyssey-server.sh
        - name: config-volume
          mountPath: /etc/script_exporter/config.yaml
          subPath: script_exporter-config.yaml
    - name: buccaneer-statsserver
      image: tensorworks/buccaneerdemo-statsserver:latest
      ports:
        - name: buccaneer-stats
          containerPort: 8000
          protocol: TCP
      requests:
        cpu: 256m
        memory: 256Mi
      limits:
        cpu: 256m
        memory: 256Mi
  volumes:
    - name: config-volume
      configMap:
        name: odyssey-server
        defaultMode: 0o755
    - name: bigquery-writer-serviceaccount
      secret:
        secretName: bigquery-writer-serviceaccount
    - name: firebase-write-serviceaccount
      secret:
        secretName: firebase-write-serviceaccount
    - name: logs
      emptyDir:
        defaultMode: 0o777
    - name: tmp
      emptyDir:
        defaultMode: 0o777
