apiVersion: v1
kind: ConfigMap
metadata:
  name: odyssey-client-custom
  app: odyssey-client-custom
  organizationId: ""
  roomId: ""
  userId: ""
  deviceId: ""
  deploymentId: ""
  firebaseProjectId: ""
data:
  config.json: |
    {
      "UseFrontend": false,
      "UseMatchmaker": false,
      "UseHTTPS": false,
      "UseAuthentication": false,
      "LogToFile": true,
      "LogVerbose": true,
      "HomepageFile": "player.html",
      "AdditionalRoutes": {},
      "EnableWebserver": true,
      "MatchmakerAddress": "",
      "MatchmakerPort": 9999,
      "PublicIp": "localhost",
      "HttpPort": 8080,
      "HttpsPort": 443,
      "StreamerPort": 8888,
      "SFUPort": 8889,
      "MaxPlayerCount": -1,
      "peerConnectionOptions": "{\"iceServers\": [{\"urls\": [\"stun:stun.l.google.com:19302\"]}]}"
    }
immutable: true
