# yamllint disable rule:line-length
---
apiVersion: v1
kind: Pod
metadata:
  name: unreal-project-version-volume-copy
  labels:
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - ORD1
  volumes:
    - name: unreal-project-version-builder-serviceaccount
      secret:
        secretName: unreal-project-version-builder-serviceaccount
    - name: unreal-project-version-volume-copy-configmap
      configMap:
        name: unreal-project-version-volume-copy
        defaultMode: 0o755
    - name: unreal-project-version-content
      persistentVolumeClaim:
        readOnly: false
        claimName: unreal-project-version-content
  restartPolicy: Never
  imagePullSecrets:
    - name: ngp-odyssey-gcr-read
  schedulerName: prioritize-image-locality
  containers:
    - name: copier
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 2000m
          memory: 4Gi
      image: gcr.io/ngp-odyssey/unreal-project-version-builder:5.2.1
      command:
        - "/bin/sh"
        - "-c"
        - 'cd /project && /scripts/entrypoint.sh'
      env:
        - name: FIREBASE_PROJECT_ID
          value:
        - name: ORGANIZATION_ID
          value:
        - name: UNREAL_PROJECT_NAME
          value:
        - name: UNREAL_PROJECT_ID
          value:
        - name: UNREAL_PROJECT_VERSION_ID
          value:
        - name: UNREAL_PROJECT_VERSION_PACKAGE_SHA256SUM
          value:
        - name: UNREAL_PROJECT_VERSION_PACKAGE_DOWNLOAD_URL
          value:
        - name: TARGET
          value:
        - name: LEVEL_NAME
          value:
        - name: LEVEL_FILE_PATH
          value:
        - name: REGION
          value:
        - name: PROJECT_DIR
          value:
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: unreal-project-version-builder-serviceaccount
          mountPath: /unreal-project-version-builder-serviceaccount
        - name: unreal-project-version-volume-copy-configmap
          mountPath: /scripts
        - name: unreal-project-version-content
          mountPath: /content
