apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: odyssey-client-node-image-pull
spec:
  selector:
    matchLabels:
      name: odyssey-client-node-image-pull
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        name: odyssey-client-node-image-pull
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-accelerator
                  operator: Exists
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: present
          effect: NoSchedule
      restartPolicy: Always
      imagePullSecrets:
        - name: ngp-odyssey-gcr-read
      containers:
        - name: unreal
          image: gcr.io/ngp-odyssey/odyssey-client:latest
          imagePullPolicy: Always
          command: ["sleep", "infinity"]
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
        - name: signallingwebserver
          image: gcr.io/ngp-odyssey/signallingwebserver:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
          command: ["sleep", "infinity"]
        - name: signallingproxy
          image: gcr.io/ngp-odyssey/signallingproxy:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
          command: ["sleep", "infinity"]
