#!/bin/sh
utcnow() {
    date --utc +%Y%m%d%H%M%S
}

log() {
    echo "$(date --utc) - $*"
}

loginfo() {
    log "INFO: $*"
}

logerror() {
    log "ERROR: $*"
}

logfatal() {
    logerror "$@"
    exit 1
}

[ -z "${FIREBASE_PROJECT}" ] && logfatal "FIREBASE_PROJECT missing"
export GCLOUD_PROJECT=$FIREBASE_PROJECT

for collection in \
    "organizations" \
    "participants" \
    "rooms" \
    "historicRooms" \
    "historicParticipants" \
    "users" \
    "deployments" \
    "invites" \
    "configurations" \
    "system" \
    "odysseyClient" \
    "odysseyServer" \
    "operations" \
    "versions" \
    ; do
    loginfo "Running for collection $collection"
    npx @firebaseextensions/fs-bq-import-collection \
        --non-interactive \
        -P "$FIREBASE_PROJECT" \
        -s $collection \
        -q true \
        -d firestore_export \
        -t $collection \
        -l us-central1 \
        -m false \
        ;
done
