#!/bin/sh
curl -svq -H 'Content-Type: application/json' \
    -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE5MGFkMTE4YTk0MGFkYzlmMmY1Mzc2YjM1MjkyZmVkZThjMmQwZWUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbmdwLW9keXNzZXkiLCJhdWQiOiJuZ3Atb2R5c3NleSIsImF1dGhfdGltZSI6MTY5NDQyMTQzNiwidXNlcl9pZCI6IjM4OVlqWG9QRU9lRWhyQzVqVUhGSlYxc2lWYTIiLCJzdWIiOiIzODlZalhvUEVPZUVockM1alVIRkpWMXNpVmEyIiwiaWF0IjoxNjk0Njg3MTQ0LCJleHAiOjE2OTQ2OTA3NDQsImVtYWlsIjoiYnJhbUBuZXdnYW1lcGx1cy5saXZlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYnJhbUBuZXdnYW1lcGx1cy5saXZlIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.FwUQUzGJnwfysZYWvRn-03l2cmC0RfJsqB7j-BSlimTOhxPoK-VWXeATxyoU-RxlqklF2vWlhbLPM_aCYOiEaAiqeuiuMFKFGGkGwXUwtjyNNdMO2UAz1FXRNOza6-I7YyundTjQ5m6hGl4t4_MxA0vXYcB2y1cwRRA8azPnNqGd_EbVpxh_6-a-ShyNl7ukvlua1gm4cixwZagcyf2ATbCTJfS2TqlSGelORHzX_nuBMfXRIYbACezX8H5mLuAmJYzXC9akJr3Wf8a4KMsgl-h9xdYFQB_nYq9t80O5d5mvGK7aScb5fhAYxk9oRLDYd7uwTabH77W_3A87yQgAcQ" \
    -X POST 'https://us-central1-ngp-odyssey.cloudfunctions.net/unrealProjects-notifyUnrealProjectVersionUploaded' \
    --data \
'
{ "data":
{
    "organizationId": "GYByxtyzprqEuwWzekiK",
    "unrealProjectId": "pSB3kK2PhHgnHXkleRdH",
    "unrealProjectVersionId": "itrtvDTeCMBZ41oPKnbwAy"
}
}'
