declare const objectGbPerMonth = 0.026;
declare const downloadPerGb = 0.12;
declare const cpuPerHour = 0.035;
declare const pvcPerMonth = 0.07;
declare const projectSizeGb = 20;
declare const packagedSizeGb: number;
declare const buildTimeHours: number;
declare const buildCpus = 16;
declare const regionCount = 3;
declare const volumeCopyCpus = 2;
declare const volumeCopyTimeHours: number;
declare const packageDownloadCost: number;
declare const projectDownloadCost: number;
declare const projectStorageCostMonth: number;
declare const packageStorageCostMonth: number;
declare const pvcCostMonthly: number;
declare const builderCost: number;
declare const volumeCopyDownloadCost: number;
declare const volumeCopyComputeCost: number;
declare const monthly: number;
declare const buildCost: number;
